spring:
    application:
        name: GlobalException

logging:
  pattern:
    # %d(??), %X{traceId}(??? ?? ???), %-5level(INFO, ERROR ?? ??), %msg(?? ???) ??? ????? ?
    console: "[%d{yyyy-mm-dd HH:mm:ss}] [%x{traceId}] %-5level - %msg%n"